### ISSUE TITLE
Volume Percentage Underneath DJ History

### ISSUE THREAD

**Issue by gyroninja** [tgicn/NightcoreIssues#55]
https://i.gyazo.com/0519ab27ae1a07282190f20564aad39b.png

Firefox 42.0 Linux

**Comment by tgicn** [comment]
Fixed in latest update

**Comment by gyroninja** [comment]
This does not appear to be fixed.
Current: https://i.gyazo.com/8540cd9264ccac37ae5d98860af0f6cb.png
With Opacity Turned Down on Buttons: https://i.gyazo.com/6657038b6dc0b79e5bab742cd54c0a52.png

**Comment by gyroninja** [comment]
@tgicn Can we have this bug reopened?

**Comment by gyroninja** [comment]
This is still an issue. Can someone re open this issue? @tgicn
